import mongoose from "mongoose";
import IJutsu from "../models/IJutsu";

export const JutsusMock = [
  {
    _id: new mongoose.Types.ObjectId("1234893fb1004c98474d0fac"),
    names: {
      englishName: "Rasengan",
      kanjiName: "螺旋丸",
      romajiName: "Rasengan",
      literalEnglish: "Spiralling Sphere",
      englishGames: "Power Strike",
      englishAnime: "",
      vizPrintMedia: "",
      alternativeNames: "Spiral Chakra Sphere",
    },
    debut: {
      manga: "Volume #17, Naruto Chapter #150",
      anime: "Naruto Episode #86",
      novel: "Road to Ninja: Naruto the Movie",
      movie: "Naruto the Movie: Ninja Clash in the Land of Snow",
      game: "Naruto: Ultimate Ninja 2",
      ova: "Finally a clash! Jonin vs. Genin!! Indiscriminate Grand Melee Tournament Meeting!!",
    },
    data: {
      classification: ["Ninjutsu"],
      kekkeiGenkai: [],
      type: [],
      class: ["Offensive"],
      range: ["Short range (0-5m)"],
      rank: "A-rank",
      handSeals: "",
    },
    images: [
      {
        src: "https://static.wikia.nocookie.net/naruto/images/2/28/Rasengan.png/revision/latest/scale-to-width-down/350?cb=20150702135410",
        alt: "",
      },
    ],
    description:
      "The Rasengan is a spinning ball of chakra formed and held in the palm of the user's hand, which is only known to a handful of shinobi.",
    relatedJutsu: ["Tailed Beast Ball"],
    parentJutsu: [],
    derivedJutsu: [
      "Big Ball Rasengan",
      "Big Ball Spiralling Serial Zone Spheres",
      "Planetary Rasengan",
      "Spiralling Absorption Sphere",
      "Ultra-Big Ball Rasengan",
      "Compression Rasengan",
      "Super Compression Rasengan",
      "Deep Crimson Spiral",
      "Gentle Step Spiralling Twin Lion Fists",
      "Guts Rasengan",
      "Parent and Child Rasengan",
      "Planetary Rasengan",
      'Rasengan: "Unison"',
      "Runt Ball Rasengan",
      "Sage Art: Magnet Release Rasengan",
      "Spiralling Bullet",
      "Spiralling Serial Spheres",
      "Spiralling Strife Spheres",
      "Student and Teacher: Rasengan",
      "Supreme Ultimate Rasengan",
      "Tailed Beast Rasengan",
      "Tornado Rasengan",
      "Ultra-Many Spiralling Serial Spheres",
      "Sage Art: Many Ultra-Big Ball Spiralling Serial Spheres",
      "Vanishing Rasengan",
      "Wind Release: Rasengan",
      "Rasengan: Flash",
      "Typhoon Water Vortex Technique",
      "Wind Release: Rasenshuriken",
    ],
    users: [
      "Boruto Uzumaki",
      "Jiraiya",
      "Kakashi Hatake",
      "Koji Kashin",
      "Konohamaru Sarutobi",
      "Minato Namikaze",
      "Momoshiki Otsutsuki",
      "Naruto Uzumaki",
      "Hiruko",
      "Breeze Dancer",
    ],
    createdAt: new Date("2022-08-20T02:04:01.896Z"),
  },
  {
    _id: new mongoose.Types.ObjectId("4321893fb1004c98474d0fac"),
    names: {
      englishName: "Chidori",
      kanjiName: "千鳥",
      romajiName: "Chidori",
      literalEnglish: "One Thousand Birds",
      englishGames: "",
      englishAnime: "",
      vizPrintMedia: "",
      alternativeNames:
        "Lightning Release: Chidori (雷遁・千鳥, Raiton: Chidori, English TV: Lightning Style: Chidori, literally meaning: Lightning Release: One Thousand Birds)",
    },
    debut: {
      manga: "Volume #13, Naruto Chapter #113",
      anime: "Naruto Episode #67",
      novel: "Naruto: Mission: Protect The Waterfall Village! (novel)",
      movie: "Naruto the Movie: Ninja Clash in the Land of Snow",
      game: "Naruto: Konoha Ninpocho",
      ova: "Finally a clash! Jonin vs. Genin!! Indiscriminate Grand Melee Tournament Meeting!!",
    },
    data: {
      classification: ["Ninjutsu"],
      kekkeiGenkai: ["Sharingan"],
      type: ["Lightning Release"],
      class: ["Offensive"],
      range: ["Short range (0-5m)"],
      rank: "A-rank",
      handSeals:
        "Ox → Rabbit → Monkey or Monkey → Dragon → Rat → Bird → Ox → Snake → Dog → Tiger → Monkey",
    },
    images: [
      {
        src: "https://static.wikia.nocookie.net/naruto/images/5/50/Sasuke%27s_chidori.png/revision/latest/scale-to-width-down/350?cb=20220118071928",
        alt: "",
      },
    ],
    description:
      "The Chidori is a high concentration of lightning chakra channelled around the user's hand.",
    relatedJutsu: [],
    parentJutsu: [],
    derivedJutsu: [
      "Chidori Current",
      "Sword of Kusanagi: Chidori Katana",
      "Chidori Senbon",
      "Chidori Sharp Spear",
      "Lightning Cutter",
      "Kamui Lightning Cutter",
      "Lightning Release: Lightning Beast Tracking Fang",
      "Lightning Transmission",
      "Susanoo: Chidori",
    ],
    users: ["Kakashi Hatake", "Sasuke Uchiha", "Sarada Uchiha"],
    createdAt: new Date("2022-08-20T21:39:30.575Z"),
  },
] as IJutsu[];
